### PR TITLE
feat: add self-starring for the starboard

### LINKED ISSUE #569: request: toggle self starring for starboard
**Is your feature request related to a problem? Please describe.**

Starboard currently blocks users from self-starring messages, with no option for toggling it on and off.

**Describe the solution you'd like**

Ability to toggle self starring for starboard.

**Describe alternatives you've considered**

none at the moment

### PR DESCRIPTION
**Pull request by cfanoulis**
pretty much draft. needs testing

Closes #569

### CODE REVIEW

**Comment by Rexogamer** [comment]
what is this gonna do exactly, is it for banning self stars

**Comment by cfanoulis** [comment]
@Rexogamer #569

**Review by Stitch07 — CHANGES_REQUESTED** [review]
You need to write a new TypeORM migration to add the column, and update src/lib/schemas/Guilds.ts.

**Comment by cfanoulis** [comment]
closing as it has been made from the wrong branch

**Pull request closed without merging**
