### PR TITLE
feat(i18n): handle new v8 permissions

### PR DESCRIPTION
**Pull request by kyranet**
While we don't support Discord v8 yet, it's worth it to support the new permissions ahead of time, so when we upgrade, we have one less thing to take care of.

### CODE REVIEW

**Comment by favna** [comment]
I don't see the permissions for stage channels? There's 2 new ones for that.

**Comment by kyranet** [comment]
> I don't see the permissions for stage channels? There's 2 new ones for that.

The new permissions are `REQUEST_TO_SPEAK` (exclusive to stage channels) and `USE_APPLICATION_COMMANDS` (slash commands).

**Review by favna — APPROVED** [review]

**Comment by vladfrangu** [comment]
> > I don't see the permissions for stage channels? There's 2 new ones for that.
> 
> The new permissions are `REQUEST_TO_SPEAK` (exclusive to stage channels) and `USE_APPLICATION_COMMANDS` (slash commands).

so chop chop and add those too

**Review by vladfrangu — APPROVED** [review]

**Comment by kyranet** [comment]
> > > I don't see the permissions for stage channels? There's 2 new ones for that.
> > 
> > 
> > The new permissions are `REQUEST_TO_SPEAK` (exclusive to stage channels) and `USE_APPLICATION_COMMANDS` (slash commands).
> 
> so chop chop and add those too

Those were added with this PR, that's why there are 4 new lines.

**Pull request merged**
