### PR TITLE
feat(leaderboard): make the message paginated

### PR DESCRIPTION
**Pull request by kyranet**
- feat(leader-board): make the message paginated
- refactor(leader-board): show external users as unknown
- refactor(routes): removed global leader board
- refactor(routes): show external users as unknown in local leader board

The reason why users are now shown as unknown when they're external, is to protect data leaks (such as users who use Skyra privately being shown in the global one), which can be very undesirable.

Other bots also show external members as unknown, too.

### CODE REVIEW

**Review by vladfrangu — DISMISSED** [review]
Test it then LGTM

**Review by favna — DISMISSED** [review]
UserLazyPaginatedMessage and UserPaginatedMessage should really be backported to Sapphire...

Also what Vladdy said.

**Comment by kyranet** [comment]
> Test it then LGTM

It's tested.

---

Also, on a side note, since we're making this protect privacy, should we also remove global leaderboard and expose only the position?

cc: @Favna @vladfrangu

**Comment by favna** [comment]
> Also, on a side note, since we're making this protect privacy, 

image

**Comment by kyranet** [comment]
> > Also, on a side note, since we're making this protect privacy,
> 
> image

Please read the PR's description

**Comment by favna** [comment]
> Also, on a side note, since we're making this protect privacy, should we also remove global leaderboard and expose only the position?

yes

**Review by favna — APPROVED** [review]

**Pull request merged**
